---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:  
  Stage:
    Type: String
  EKSIAMRole:
    Type: String
    Description: The name of the IAM role for the EKS service to assume.    
  EKSClusterName:
    Type: String
    Description: The desired name of your AWS EKS Cluster.
  ControlPlaneSecurityGroup:
    Type: String
    Description:  Security group for the control plane 
  PublicSubnet01:
    Type: String
    Description: public subnet 01 within the VPC  
  PublicSubnet02:
    Type: String
    Description: public subnet 02 within the VPC  
  PrivateSubnet01:
    Type: String
    Description: private subnet 01 within the VPC  
  PrivateSubnet02:
    Type: String
    Description: private subnet 02 within the VPC

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      Version: "1.21"
      RoleArn: !Join ["", ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/', !Ref EKSIAMRole]] 
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds:
          - !Ref PublicSubnet01
          - !Ref PublicSubnet02
          - !Ref PrivateSubnet01
          - !Ref PrivateSubnet02
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
        #PublicAccessCidrs: [ "1.1.1.2/32" ]
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: "env"
          Value: "dev"
