EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: Test
      Version: "1.23"
      RoleArn: "arn:aws:iam::835958603956:role/EKSAccessRole"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-068f4a7a5a3f147a1
        SubnetIds:
          - subnet-075d4e18e1708a9f9
          - subnet-02af07e51863b8382
          - subnet-00b41774b536f281f
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
        PublicAccessCidrs: [ "1.1.1.2/32" ]
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: "env"
          Value: "test"