AWSTemplateFormatVersion: '2010-09-09'
Description: Create an IAM Role for EKS
Parameters:  
  Stage:
    Type: String

Resources:
  EKSAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role to manage EKS
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      RoleName: EKSAccessRole
Outputs:
  EKSAccessRole:
    Description: The EKS Role Name
    Value: !Ref EKSAccessRole
